engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
       ruby:
       javascript:
          mass_threshold: 115
       python:
       php:
          mass_threshold: 140
  eslint:
    enabled: true
    checks:
      no-irregular-whitespace:
        enabled: false
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- config/
- tests/
- public/
